version: '3.9'

services:
  flask:
    container_name: flask
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./gunicorn_conf:/gunicorn
    environment:
      - MODULE_NAME=app.main
      - GUNICORN_CONF=/gunicorn/gunicorn_conf.py
    networks:
      - bridge
    environment:
      - PUB_PASSWORD=${PUB_PASSWORD}
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - PAGE_ACCESS_TOKEN=${PAGE_ACCESS_TOKEN}

  haproxy:
      container_name: haproxy
      image: haproxy:latest
      restart: always
      depends_on:
        - flask
      ports:
          - 80:80
          - 443:443
      volumes:
        - ./haproxy_conf:/usr/local/etc/haproxy:ro
        - ../certs:/certs:ro
      networks:
        - bridge

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto_conf:/mosquitto/config:rw
    ports:
      - 1883:1883
    networks:
      - bridge
    entrypoint: /mosquitto/config/create_users.sh
    command:  ["/usr/sbin/mosquitto", "-c","/mosquitto/config/mosquitto.conf"]
    environment:
      - PUB_PASSWORD=${PUB_PASSWORD}
      - SUB_PASSWORD=${SUB_PASSWORD}

networks:
  bridge:
    driver: bridge
